const CONFIG = {
    url:'https://summer.langjie.com/summer',
    pathName:'',
    menus:[
        {
            id:'0',
            tetx:'首页',
            key:'index',
            path:'/Index',
            subMenus:[]
        },
        {
            id:'1',
            text:'小程序名称一',
            key:'miniNameOne',
            path:'/miniOne',
            subMenus:[
                {
                    id:'1-1',
                    text:'管理一',
                    key:'miniOneManage1',
                    subpath:'/miniOne/manage1'
                },
                {
                    id:'1-2',
                    text:'管理二',
                    key:'miniOneManage2',
                    subpath:'/miniOne/manage2'
                }
            ]
        },
        {
            id:'2',
            text:'小程序名称二',
            key:'miniNameTwo',
            path:'/miniTwo',
            subMenus:[
                {
                    id:'2-1',
                    text:'管理三',
                    key:'miniTwoManage1',
                    subpath:'/miniTwo/manage1'
                },
                {
                    id:'2-2',
                    text:'管理四',
                    key:'miniTwoManage2',
                    subpath:'/miniTwo/manage2'
                }
            ]
        },
    ]
}

export default CONFIG